### ISSUE TITLE
Scroll lagging/slow performance

### ISSUE THREAD

**Issue by yarnball** [clauderic/react-tiny-virtual-list#12]
Hi,

This looks like a great little add on (only 3kb's!).

I'm having some difficultly implementing. I tried following your example, but had no success. T

I had *some* success. But performance isn't great. The scroll is laggy. I've probably implemented it wrong.

See here https://codesandbox.io/s/vo1xjpxrL

Here's the code:

```
class App extends React.Component {
  constructor() {
    super();
    this.state = {
      demoData: x.demoData,
    };
  }
  render() {
    return (
        <VirtualList
    width='100%'
    height={800}
    itemCount={this.state.demoData.length}
    itemSize={50}
    renderItem={({index, style}) =>
      <div style={style} key={index}> 
{this.state.demoData.map(e => {
          return <Result e={e}/>;
        })[index]}
      </div>
    }
  />

    );
  }
}

class Result extends React.Component {
  render() {
    const { e, remove } = this.props;

    return (
      <div key={e.id}>
        {e.name} {' '} {e.id}
      </div>
    );
  }
}
```

Cheers,

**Comment by clauderic** [comment]
Right off the bat, your `renderItem` prop should be a class method, otherwise a new function gets re-created every single time `render()` is called, which in turn causes `VirtualList` to re-render, since it's props change when that happens.

Depending on how complex your rows are though, it's possible this is just a limitation with React. I see you're mapping multiple results per row, so depending on how many results you're mapping, this could be a source of performance issues.

You can also try lowering the `overscanCount` prop to reduce the number of rows that are rendered on screen.

**Comment by clauderic** [comment]
Ah, you were mapping through your entire dataset for every single row, instead of just accessing the right dataset for the row being rendered. Take a look at: https://codesandbox.io/s/1wqGN4WgG

**Comment by yarnball** [comment]
Can you please help me out with this- I am still very stuck on it

**Comment by odinous95** [comment]
Check if you have
```
 html{
  scroll-behavior: smooth;
}
```
in your index.css or somewhere if so then delete it because, it  causes some issues with react-scrolling.
