### ISSUE TITLE
Umd build error - prop-types is not included in the build

### ISSUE THREAD

**Issue by vegetableman** [clauderic/react-tiny-virtual-list#20]
Those who may encounter the proptype error on umd build, the following script needs to be added manually to fix it :
`<script src="https://unpkg.com/prop-types/prop-types.js"></script>`

cc @clauderic

**Comment by clauderic** [comment]
@vegetableman This is intentional. PropTypes, just like React and ReactDOM is as an external dependency. This is to avoid having multiple different versions of the same code bundled in your app. 

If it were included in the build, it would mean that you might end up with multiple different copies of PropTypes running at the same time, which could cause issues and would add useless bloat to your application.
