### ISSUE TITLE
Issues with the list when attaching to iOS homescreen

### ISSUE THREAD

**Issue by Shaked** [clauderic/react-tiny-virtual-list#33]
Hey, I am experiencing some issues with the list when attaching to iOS homescreen. Not sure if I should file a bug as I read it might be better to talk about it here first. I made a video of the issue using iPad mini 2:

iPad Screencast: https://youtu.be/KIDnUovmGVo
Example: https://pymwymi.io/clusterizejs/reactjs/index.html
Code: https://gist.github.com/Shaked/6b9d7e22a0b8ef3b5754c017fad4cf33

Thank you,
Shaked

P.S
I also tried to create the same example without ReactJS and experienced similar issues: 
https://github.com/NeXTs/Clusterize.js/issues/130 
Maybe it's a iOS/Safari bug?

**Comment by clauderic** [comment]
Hey @Shaked,

I don't believe this is specifically an issue with `react-tiny-virtual-list`. It looks like a performance issue, where the device cannot render the requested rows fast enough since your rows are quite heavy to render (multiple images per row).

The difference in behaviour between when you look at your app in Safari vs an app added to HomeScreen is because of the webview used is different. When you look at the app in Safari, it uses `WKWebView`, which is significantly more performant than `UIWebView`, which is the webview used for web pages added to the home screen. I don't believe you can specify for a web page added to the home screen to run using `WKWebView`

You could look into bundling your app using Cordova instead, which would allow you to specify which webview is used and select `WKWebView`.
